bn_platform_homepage:
    path:     /accueil
    defaults: { _controller: BNPlatformBundle:Advert:accueil }

bn_connexion:
    path:    /connexion
    defaults: { _controller: BNPlatformBundle:Advert:connexion}
bn_confirm:
    path:    /confirm
    defaults: { _controller: BNPlatformBundle:Advert:valid}

#bn_log_in:
 #   path:    /login
  #  defaults: { _controller: BNPlatformBundle:Advert:login}
bn_add:
    path:    /add
    defaults: { _controller: BNPlatformBundle:Advert:add}