#bn_user:
 #   resource: "@BNUserBundle/Resources/config/routing.yml"
  #  prefix:   /

bn_platform:
    resource: "@BNPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:  /login
    defaults:
      _controller: BNUserBundle:Security:login
login_check:
    path:  /login_check
logout:
    path:  /logout
