# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #provider: in_memory

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        BN\UserBundle\Entity\User: sha512
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:    
        #in_memory:
         #  memory: 
          #  users:
           #     user: { password: userpass, roles: ['ROLE_USER'] }
            #    admin: { password: adminpass, roles: ['ROLE_ADMIN'] }
        main:
            #entity:
                #class:    BN\UserBundle\Entity\User
                #property: username
                # on utilise le provider de fos 
            id: fos_user.user_provider.username   
    access_control:

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /bn_forum_test #redirige la page après login
            logout:
                path:    fos_user_security_logout
                target:    fos_user_security_login
            remember_me:
                secret: '%secret%'
