<?php

namespace BN\ForumBundle\Repository;

/**
 * forum_topicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class forum_topicRepository extends \Doctrine\ORM\EntityRepository
{
}
