<?php

namespace BN\ForumBundle\Repository;

/**
 * forum_postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class forum_postRepository extends \Doctrine\ORM\EntityRepository
{
}
