<?php

namespace BN\ForumBundle\Repository;

/**
 * forum_membresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class forum_membresRepository extends \Doctrine\ORM\EntityRepository
{
}
